import json

with open("data.json", "r") as f:
    data = json.load(f)

# assign variables from json file
GROUND_ROLE_HIERARCHY = data["GROUND_ROLE_HIERARCHY"]
GROUND_ROLE_PREFIX = data["GROUND_ROLE_PREFIX"]
NCO_ROLE_HIERARCHY = data["NCO_ROLE_HIERARCHY"]
NCO_ROLE_PREFIX = data["NCO_ROLE_PREFIX"]
AIR_ROLE_HIERARCHY = data["AIR_ROLE_HIERARCHY"]
AIR_ROLE_PREFIX = data["AIR_ROLE_PREFIX"]
ARMOR_ROLE_HIERARCHY = data["ARMOR_ROLE_HIERARCHY"]
ARMOR_ROLE_PREFIX = data["ARMOR_ROLE_PREFIX"]
AUTHORIZED_ROLES = data["AUTHORIZED_ROLES"]
SILLY_FACT_CHECK_POSITIVE = data["SILLY_FACT_CHECK_POSITIVE"]
SILLY_FACT_CHECK_NEGATIVE = data["SILLY_FACT_CHECK_NEGATIVE"]
ROLE_DICTIONARY = data["ROLE_DICTIONARY"]
CLIENT_SIDE_MOD_LIST = data["CLIENT_SIDE_MOD_LIST"]
